export const ADDRESS_DIALOG = 'ADDRESS_DIALOG'
export const CONTACT_DIALOG = 'CONTACT_DIALOG'
export const SAVE_ADDRESS = 'SAVE_ADDRESS'
export const DELETE_ADDRESS = 'DELETE_ADDRESS'
export const SAVE_CONTACT = 'SAVE_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const GET_PATIENT_DATA = 'GET_PATIENT_DATA'
export const RESET_PATIENT_DATA = 'RESET_PATIENT_DATA'

export default {
  ADDRESS_DIALOG,
  CONTACT_DIALOG,
  DELETE_ADDRESS,
  SAVE_ADDRESS,
  DELETE_CONTACT,
  SAVE_CONTACT,
  GET_PATIENT_DATA,
  RESET_PATIENT_DATA
}
