export const ADDRESS_DIALOG = 'ADDRESS_DIALOG'
export const CONTACT_DIALOG = 'CONTACT_DIALOG'
export const SAVE_ADDRESS = 'SAVE_ADDRESS'
export const DELETE_ADDRESS = 'DELETE_ADDRESS'
export const SAVE_CONTACT = 'SAVE_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const GET_ID = 'GET_ID'
export const GET_LIST = 'GET_LIST'
export const RESET_ID = 'RESET_ID'
export const RESET_LIST = 'RESET_LIST'
export const SAVE = 'SAVE'
export const CREATE = 'CREATE'
export const DELETE = 'DELETE'
export const GENERATE_RECORD = 'GENERATE_RECORD'

export default {
  ADDRESS_DIALOG,
  CONTACT_DIALOG,
  DELETE_ADDRESS,
  SAVE_ADDRESS,
  DELETE_CONTACT,
  SAVE_CONTACT,
  GET_ID,
  GET_LIST,
  RESET_ID,
  RESET_LIST,
  SAVE,
  CREATE,
  DELETE,
  GENERATE_RECORD
}
