export const ADDRESS_DIALOG = 'ADDRESS_DIALOG'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CONTACT_DIALOG = 'CONTACT_DIALOG'
export const GET_DATA_USER = 'GET_DATA_USER'
export const RESET_DATA_USER = 'RESET_DATA_USER'
export const PASSWORD_DIALOG = 'PASSWORD_DIALOG'
export const SAVE_USER = 'SAVE_USER'
export const SAVE_ADDRESS = 'SAVE_ADDRESS'
export const DELETE_ADDRESS = 'DELETE_ADDRESS'
export const SAVE_CONTACT = 'SAVE_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'

export default {
  ADDRESS_DIALOG,
  CHANGE_PASSWORD,
  CONTACT_DIALOG,
  GET_DATA_USER,
  RESET_DATA_USER,
  PASSWORD_DIALOG,
  SAVE_USER,
  SAVE_ADDRESS,
  DELETE_ADDRESS,
  SAVE_CONTACT,
  DELETE_CONTACT
}
