export const ADDRESS_DIALOG = 'ADDRESS_DIALOG'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CONTACT_DIALOG = 'CONTACT_DIALOG'
export const CREATE_USER = 'CREATE_USER'
export const GET_USER = 'GET_USER'
export const DELETE_USER = 'DELETE_USER'
export const RESET_USER = 'RESET_USER'
export const GET_USER_LIST = 'GET_USER_LIST'
export const RESET_USER_LIST = 'RESET_USER_LIST'
export const SAVE_USER = 'SAVE_USER'
export const SAVE_ADDRESS = 'SAVE_ADDRESS'
export const DELETE_ADDRESS = 'DELETE_ADDRESS'
export const SAVE_CONTACT = 'SAVE_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'

export default {
  ADDRESS_DIALOG,
  CHANGE_PASSWORD,
  CONTACT_DIALOG,
  CREATE_USER,
  DELETE_USER,
  GET_USER,
  RESET_USER,
  GET_USER_LIST,
  RESET_USER_LIST,
  SAVE_USER,
  SAVE_ADDRESS,
  DELETE_ADDRESS,
  SAVE_CONTACT,
  DELETE_CONTACT
}
