export const CURRENT_USER = 'CURRENT_USER'
export const SIGNIN_USER = 'SIGNIN_USER'
export const SIGNOUT_USER = 'SIGNOUT_USER'
export const RECOVER_PASSWORD = 'RECOVER_PASSWORD'
export const RECOVERY_DIALOG = 'RECOVERY_DIALOG'
export const RESET_PASSWORD = 'RESET_PASSWORD'

export default {
  CURRENT_USER,
  SIGNIN_USER,
  SIGNOUT_USER,
  RECOVER_PASSWORD,
  RECOVERY_DIALOG,
  RESET_PASSWORD
}
